=== IDRISSI1998/Catalog-of-Moroccan-schools-and-universities/ecoles.dtd
<!ELEMENT gestion_ecole (universite|ecole)*>

<!ATTLIST universite type CDATA "public">
<!ATTLIST ecole type CDATA "public">

<!ELEMENT universite (nom, date-creation, composantes, descriptif, image, adresse, site, email, telephones)>
<!ELEMENT ecole (nom, date-creation, categorie, descriptif, image, adresse, site, email, telephones, diplomes)>

<!ELEMENT nom (#PCDATA)*>
<!ATTLIST nom acronyme CDATA "">
<!ELEMENT date-creation (#PCDATA)*>
<!ELEMENT descriptif (#PCDATA)*>
<!ELEMENT image (#PCDATA)*>
<!ELEMENT adresse (#PCDATA)*>
<!ELEMENT site (#PCDATA)*>
<!ELEMENT email (#PCDATA)*>
<!ELEMENT telephones (telephone)*>
<!ELEMENT telephone (#PCDATA)*>




<!ELEMENT composantes (#PCDATA)*>


<!ELEMENT categorie (#PCDATA)*>
<!ELEMENT diplomes (diplome)*>
<!ELEMENT diplome (nom, duree, filieres)>
<!ELEMENT duree (#PCDATA)*>
<!ELEMENT filieres (filiere)*>
<!ELEMENT filiere (nom, descriptif)>

=== IDRISSI1998/Catalog-of-Moroccan-schools-and-universities/ecoles.xml
<?xml version ="1.0" ?>
<?xml-stylesheet type ="text/xsl" href ="ecoles.xsl" ?>

<!DOCTYPE gestion_ecole SYSTEM "ecoles.dtd">


<gestion_ecole>
   
    
   <universite type="public">
      <nom acronyme="UM5">L'université Mohammed-V de Rabat</nom>
      <date-creation>1957</date-creation>
      <composantes>18 etablissements affiliés dont 5 Instituts de recherche</composantes>
      <descriptif>L'université Mohammed-V de Rabat est une université marocaine située à Rabat. Elle est officiellement inaugurée par le roi Mohammed V, le 21 décembre 19571. En 1994-1995, elle s'est divisée en deux universités indépendantes – l'université Mohammed V - Agdal, dans le quartier Agdal et l'université Mohammed V - Souissi sur le campus d'Al Irfane. Le 1er septembre 2014, celles-ci fusionnent pour redonner naissance à l'université Mohammed-V de Rabat2. Pour la simplicité, l'université est parfois nommée UM5.</descriptif>
      <image>images/um5.jpg</image>
      <adresse>Avenue des Nations Unies B.P:8007 Agdal Rabat</adresse>
      <site>www.um5.ac.ma</site>
      <email>présidence@um5.ac.ma</email>
      <telephones>
         <telephone>0537671401</telephone>
         <telephone>0537272750</telephone>	
      </telephones>
   </universite>
   
   <universite type="public">
      <nom acronyme="UH2C">Université Hassan II de Casablanca</nom>
      <date-creation>2014</date-creation>
      <composantes>18 etablissements affiliés</composantes>
      <descriptif>L'université Hassan II de Casablanca (UH2C) (en amazighe : Tasdawit Leḥsen wiss sin n Kaẓa, en arabe : جامعة الحسن الثاني بالدارالبیضاء) Implantée au sein de la capitale économique du Maroc, l’université Hassan II de Casablanca est une université publique, qui répond aux missions du service public de l’enseignement supérieur, de la recherche et de l’innovation. L’université Hassan II de Casablanca a été créée en septembre 2014 après la fusion de l'université Hassan II Mohammedia et celle de Casablanca. Avec ses 6 campus, ses 18 établissements situés à Casablanca et à Mohammedia, et 84 931 étudiants composés de locaux et d'étrangers, elle est la plus grande université au Maroc.</descriptif>
      <image>images/uh2c.jpg</image>
      <adresse>19, Rue Tarik Ibnou Ziad, Mers Sultan, BP : 9167, Casablanca, Maroc</adresse>
      <site>www.univh2c.ma</site>
      <email>contact@usms.ma</email>
      <telephones>
         <telephone>06 14 00 04 00</telephone>
         <telephone>06 14 00 04 07</telephone>
      </telephones>
   </universite>
   
   <universite type="public">
      <nom acronyme="USMBA">Université Sidi Mohamed Ben Abdellah de Fès</nom>
      <date-creation>1975</date-creation>
      <composantes>12 etablissements affiliés</composantes>
      <descriptif>L'université Sidi Mohamed Ben Abdellah est une institution d’enseignement public supérieur et de recherche scientifique marocaine, à but non lucratif. Elle est située dans la ville de Fès au Maroc. Ella a été fondée le 17 octobre 1975.</descriptif>
      <image>images/usmba.jpg</image>
      <adresse>B.P : 2626, Route d’Imouzzer, Fès, Maroc</adresse>
      <site>www.usmba.ac.ma</site>
      <email>--</email>
      <telephones>
         <telephone>05 35 60 96 61</telephone>
         <telephone>05 35 60 96 60</telephone>
      </telephones>
   </universite>
   
   <universite type="public">
      <nom acronyme="UCA">Université Cadi Ayyad</nom>
      <date-creation>1978</date-creation>
      <composantes>12 etablissements affiliés</composantes>
      <descriptif>L'université Cadi Ayyad de Marrakech est une université publique fédérant les établissements d'enseignement supérieur de Marrakech, El Kelaâ des Sraghna, Essaouira et Safi. Elle est classée par le Times Higher Education1 parmi les 100 meilleures universités au monde ayant moins de 50 ans d'existence. Elle est classée par le U.S. News and World Report au 23e rang dans le classement régional 2016 des universités arabes</descriptif>
      <image>images/uca.jpg</image>
      <adresse>Av Abdelkrim Khattabi, B.P. 511 - 40000 -</adresse>
      <site>www.uit.ac.ma/</site>
      <email>ucacom@uca.com</email>
      <telephones>
         <telephone>(+212) 5 24 43 44 94</telephone>
         <telephone>(+212) 524 437 741</telephone>
      </telephones>
   </universite>
   
   <universite type="public">
      <nom acronyme="UMI">Université Moulay-Ismaïl</nom>
      <date-creation>1989</date-creation>
      <composantes>9 etablissements affiliés</composantes>
      <descriptif>L'Université Moulay-Ismaïl est une institution d'enseignement supérieur publique et de recherche scientifique à but non lucratif, située à Meknès, au Maroc. L'université a été créée le 23 octobre 1989 par le dahir no 21-86-144. Elle est classée 100e dans le classement régional 2016 des universités arabes (U.S.News and World Report)1.</descriptif>
      <image>images/umi.jpg</image>
      <adresse>Présidence, Marjane 2, BP:298, Meknes, MAROC</adresse>
      <site>www.umi.ac.ma</site>
      <email>presidence@umi.ac.ma</email>
      <telephones>
         <telephone>0535 467 305</telephone>
         <telephone>0535 467 306</telephone>
      </telephones>
   </universite>
   
   <universite type="public">
      <nom acronyme="UIZ">Université Ibn Zohr</nom>
      <date-creation>1989</date-creation>
      <composantes>15 etablissements affiliés dont 9 facultés et 6 écoles</composantes>
      <descriptif>L’université Ibn Zohr est une université marocaine située à Agadir. Elle est classée 82e dans le classement régional 2016 des universités arabes (U.S.News and World Report)</descriptif>
      <image>images/uiz.jpg</image>
      <adresse>BP 32/S, CP 80000 Agadir, Maroc</adresse>
      <site>www.uiz.ac.ma</site>
      <email>contact@uiz.ac.ma</email>
      <telephones>
         <telephone>+212528227125</telephone>
         <telephone>+2125282272606</telephone>
      </telephones>
   </universite>
   
   <universite type="public">
      <nom acronyme="UAE">Université Abdelmalek Essaâdi de Tétouan</nom>
      <date-creation>1989</date-creation>
      <composantes>15 etablissements affiliés</composantes>
      <descriptif>L'Université Abdelmalek Essaâdi est une université marocaine publique créée en 1989. Elle est considérée comme l'université principale du Nord du Royaume Marocain. Cette université est composée de 15 institutions, notamment des écoles et des établissements répartis dans la région Tanger-Tétouan-AL Hoceima et dans la ville de Larache. L'Université est classée 82e dans le classement régional 2016 des universités arabes (U.S.News and World Report)</descriptif>
      <image>images/uae.png</image>
      <adresse>Quartier M'haneche II, Avenue Palestine (près de la Faculté des Sciences), B.P : 2117, Tétouan, Maroc</adresse>
      <site>www.uae.ma</site>
      <email>presidence@uae.ac.ma</email>
      <telephones>
         <telephone>05 39 97 93 16</telephone>
      </telephones>
   </universite>
   
   <universite type="public">
      <nom acronyme="UIT">Université Ibn-Tofail de Kenitra</nom>
      <date-creation>1989</date-creation>
      <composantes>7 etablissements affiliés</composantes>
      <descriptif>L'université Ibn Tofaïl est une université publique marocaine située à Kénitra. Elle est classée 94e dans le classement régional 2016 des universités arabes</descriptif>
      <image>images/uit.jpg</image>
      <adresse>Adresse : B.P 242 Kénitra Maroc</adresse>
      <site>www.uit.ac.ma/</site>
      <email>presidence@uit.ac.ma</email>
      <telephones>
         <telephone>(+212) 6 61 40 35 57</telephone>
      </telephones>
   </universite>

   <universite type="public">
      <nom acronyme="UMP">Université Mohammed Premier d’Oujda</nom>
      <date-creation>1978</date-creation>
      <composantes>8 etablissements affiliés</composantes>
      <descriptif>L'université Mohammed Ier Créée en 1978,constitue un ensemble d'établissements de la région de l'Oriental, au Maroc, dont la majorité se trouve à Oujda. Elle est classée 32e dans le classement régional 2016 des universités arabes (U.S.News and World Report)</descriptif>
      <image>images/ump.jpg</image>
      <adresse>Boulevard Mohammed VI, B.P : 524, 60000, Oujda, Maroc</adresse>
      <site>www.ump.ma</site>
      <email>contact@ump.ac.ma</email>
      <telephones>
         <telephone>05 36 50 06 12</telephone>
         <telephone>05 36 50 06 14</telephone>
      </telephones>
   </universite>
   
   <universite type="public">
      <nom acronyme="USMS">Université Sultan Moulay Slimane de Béni Mellal</nom>
      <date-creation>2006</date-creation>
      <composantes>12 etablissements affiliés</composantes>
      <descriptif>Créée en 2006, l’Université Sultan Moulay Slimane de Béni Mellal (USMS Béni Mellal) est une université publique d’enseignement et de recherche, située couvrant la région de Béni Mellal-Khénifra et elle est considérée parmi les jeunes universités du Maroc. L’Université Sultan Moulay Slimane de Béni Mellal compte, à l’heure actuelle, sept établissements d’enseignement supérieur avec des implantations dans les villes de Béni Mellal, Khouribga, Khénifra et, prochainement, Fquih Ben Saleh. D’autres établissements viendront élargir le réseau de l’USMS Béni Mellal dans un futur proche.</descriptif>
      <image>images/usms.jpg</image>
      <adresse>Av. Med V, B.P : 591, Béni Mellal, Maroc</adresse>
      <site>www.usms.ac.ma</site>
      <email>contact@usms.ma</email>
      <telephones>
         <telephone>05 23 48 02 18</telephone>
      </telephones>
   </universite>

  



   

   <ecole type="public">
      <nom acronyme="EMI">Ecole Mohammadia d'ingénieurs</nom>
      <date-creation>1959</date-creation>
      <categorie>Ecole d'ingénieur</categorie>
